### ISSUE TITLE
deploy prod 在windows gitbash命令行报错，cmd命令行OK

### ISSUE THREAD

**Issue by tomatobybike** [dadaiwei/fe-deploy-cli#10]
$ deploy prod
error Error: Prompts can not be meaningfully rendered in non-TTY environments
    at PromptUI.fetchAnswer (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_inquirer@7.0.6@inquirer\lib\ui\prompt.js:87:27)
    at MergeMapSubscriber._tryNext (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:95:26)
    at InnerSubscriber._next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Observable.js:30:22) {
  isTtyError: true
}

**Comment by dadaiwei** [comment]
老哥，稍等，我看下我这边是不是报错

**Comment by dadaiwei** [comment]
老哥，我这边是ok的

**Comment by tomatobybike** [comment]
兄台，我是window 10 系统，默认的cmd，没问题。Mac 也没问题。
就是**### **win10的 gitbash命令行****，运行，报如上错，node版本13.8.0 ，用的nvm管理的node多版本

**Comment by dadaiwei** [comment]
好的，老哥，我装个13.8.0试试看哈

**Comment by tomatobybike** [comment]
重新安装了node，改用13.10.1 .
已经不报错了。Mac Windows完美切换
