### ISSUE TITLE
vite项目目中无法运行

### ISSUE THREAD

**Issue by huanbin111** [dadaiwei/fe-deploy-cli#21]

**Comment by huanbin111** [comment]
报错信息:   

const config = require(deployConfigPath);
                   ^

Error [ERR_REQUIRE_ESM]: require() of ES Module E:\work\xinshidai\BCP\bcp_front\deploy\deploy.config.js from D:\Users\Administrator\AppData\Roaming\nvm\v16.19.1\node_modules\fe-deploy-cli\utils\index.js not supported.
deploy.config.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename deploy.config.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in E:\work\xinshidai\BCP\bcp_front\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at checkDeployConfig (D:\Users\Administrator\AppData\Roaming\nvm\v16.19.1\node_modules\fe-deploy-cli\utils\index.js:90:20)
    at deploy (D:\Users\Administrator\AppData\Roaming\nvm\v16.19.1\node_modules\fe-deploy-cli\bin\index.js:44:27)
    at Object.<anonymous> (D:\Users\Administrator\AppData\Roaming\nvm\v16.19.1\node_modules\fe-deploy-cli\bin\index.js:33:5) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by mogenshixiong** [comment]
cd 到 deploy 目录，然后执行命令 可行吗？
