### ISSUE TITLE
deploy prod 报错 node 版本 13.8.0

### ISSUE THREAD

**Issue by tomatobybike** [dadaiwei/fe-deploy-cli#8]
$ deploy prod
(node:19896) UnhandledPromiseRejectionWarning: Error: Prompts can not be meaningfully rendered in non-TTY environments
    at PromptUI.fetchAnswer (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_inquirer@7.0.6@inquirer\lib\ui\prompt.js:87:27)
    at MergeMapSubscriber._tryNext (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:95:26)
    at InnerSubscriber._next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Observable.js:30:22)
(node:19896) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by dadaiwei** [comment]
我本地node是10.x版本

**Comment by dadaiwei** [comment]
好想是prompt库导致的，我再看下哈

**Comment by tomatobybike** [comment]
> 好想是prompt库导致的，我再看下哈

辛苦，不过，你不能复现的话，就不好改

**Comment by dadaiwei** [comment]
老哥，我升到v13.10.0后，vscode终端不报错，然后gitbash那边报错

**Comment by dadaiwei** [comment]
> > 好想是prompt库导致的，我再看下哈
> 
> 辛苦，不过，你不能复现的话，就不好改

老哥，你先npm update，然后在运行deploy prod看看是不是还是报错

**Comment by tomatobybike** [comment]
> 老哥，我升到v13.10.0后，vscode终端不报错，然后gitbash那边报错



> 老哥，我升到v13.10.0后，vscode终端不报错，然后gitbash那边报错

对的，那就是复现了？其实不影响使用，只是习惯使用gitbash命令行，不太用cmd。挺好的工具

**Comment by dadaiwei** [comment]
是的，复现了，我在前端目录下执行npm update之后，在执行deploy dev是可以的，你试试看还行

**Comment by tomatobybike** [comment]
> 是的，复现了，我在前端目录下执行npm update之后，在执行deploy dev是可以的，你试试看还行

工程目录还是deploy的安装的系统node目录

**Comment by tomatobybike** [comment]
win 10 node 13.10.1 Gitbash可以了，不报错了。

**Comment by dadaiwei** [comment]
是在工程目录哦，没报错就好了，感谢老哥的意见，非常感谢

**Comment by tomatobybike** [comment]
> 是在工程目录哦，没报错就好了，感谢老哥的意见，非常感谢

下午把环境搞坏了，重新安装了node，顺手再装了个最新的node 13.10.1，不报错。
======================
Mac 、windows都可以用了，很方便的工具 。
