### ISSUE TITLE
deploy dev 失败

### ISSUE THREAD

**Issue by tomatobybike** [dadaiwei/fe-deploy-cli#9]
$ deploy dev
error Error: Prompts can not be meaningfully rendered in non-TTY environments
    at PromptUI.fetchAnswer (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_inquirer@7.0.6@inquirer\lib\ui\prompt.js:87:27)
    at MergeMapSubscriber._tryNext (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\operators\mergeMap.js:95:26)
    at InnerSubscriber._next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Subscriber.js:66:18)
    at Observable._subscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\util\subscribeToArray.js:5:20)
    at Observable._trySubscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (D:\dev\nvm\v13.8.0\node_modules\fe-deploy-cli\node_modules\_rxjs@6.5.4@rxjs\internal\Observable.js:30:22) {
  isTtyError: true

**Comment by tomatobybike** [comment]
win 10 下 gitbash里不行，得在cmd里运行
